language: python

before_install:
  - echo "before install"

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conta install --yes -c potassco clingo
  - python3 setup.py develop --user

script:
  - cd tests/
  - ./run-tests.sh
